name: Convert Org to Markdown

on:
  push:
    branches:
      - main 

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert Org files to Markdown
      run: |
        for file in *.org; do
          pandoc "$file" -f org -t markdown -o "${file%.org}.md"
        done

    - name: Commit and push if changed
      run: |
        git config --local user.email "144010979+oddfeed@users.noreply.github.com"
        git config --local user.name "oddfeed"
        git add --all
        git commit -m "Convert Org files to Markdown" -a || echo "No changes to commit"
        git push
