name: Run Script

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run-script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run script
      run: |
        chmod +x ./script.sh
        ./script.sh
    
    - name: Commit and Push changes
      run: |
        git config --global user.email "144010979+oddfeed@users.noreply.github.com"
        git config --global user.name "oddfeed"
        git add .
        git commit -m "Automated changes from script.sh"
        git push
